### ISSUE TITLE
IntendedFor population crashing heudiconv with Siemens XA dicoms

### ISSUE THREAD

**Issue by jmatthews-rotman** [nipy/heudiconv#649] opened 2023-03-06 23:46 UTC
### Summary

Heudiconv exits when trying to populate IntendedFor fields with Siemens XA dicoms. 

### Platform details:

Choose one:
- [ ] Local environment

- [X] Container

- Heudiconv version: 0.11.6

This may overlap with existing issues related to Siemens XA AcquisitionDateTime dicom fields, and IntendedFor population. 

After updating from 0.10.0 to 0.11.6 (working on 0.12.0 update) and re-running Heudiconv (with the ReproIn heuristic) on a dataset that was previously converted without issue, I've run into a new crash. When Heudiconv starts trying to populate the IntendedFor field (which I don't recall it doing in the previous version), it encounters a ValueError checking time and finding 'n/a', but then heudiconv stops completely. This is apparent from the high level template files (e.g. dataset_description.json) not being created. 

Here is the last section of output before it quit:

INFO: Adding "IntendedFor" to the fieldmaps in /data/chen_lab/jmatthews/data/bids/Buchsbaum/Matthews/102TD_Development/sub-5591.
Traceback (most recent call last):
  File "/software/anaconda3/bin/heudiconv", line 8, in <module>
    sys.exit(main())
  File "/software/anaconda3/lib/python3.7/site-packages/heudiconv/cli/run.py", line 24, in main
    workflow(**kwargs)
  File "/software/anaconda3/lib/python3.7/site-packages/heudiconv/main.py", line 393, in workflow
    grouping=grouping,)
  File "/software/anaconda3/lib/python3.7/site-packages/heudiconv/convert.py", line 219, in prep_conversion
    dcmconfig=dcmconfig,)
  File "/software/anaconda3/lib/python3.7/site-packages/heudiconv/convert.py", line 587, in convert
    populate_intended_for(session_path, **populate_intended_for_opts)
  File "/software/anaconda3/lib/python3.7/site-packages/heudiconv/bids.py", line 915, in populate_intended_for
    criterion=criterion
  File "/software/anaconda3/lib/python3.7/site-packages/heudiconv/bids.py", line 835, in select_fmap_from_compatible_groups
    "%Y-%m-%dT%H:%M:%S.%f"
  File "/software/anaconda3/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/software/anaconda3/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data 'n/a' does not match format '%Y-%m-%dT%H:%M:%S.%f'

Happy to provide anything else needed to troubleshoot.

**Comment by yarikoptic** [comment] 2023-03-07 02:06
I think it is the duplicate of https://github.com/nipy/heudiconv/issues/612 for which there is #614 which is yet to be finished but may be you could give it a try (might need newer python though in its current state)

**Closed** 2023-03-07 02:07 UTC
