### ISSUE TITLE
Unable to pull repository/image with docker. 

### ISSUE THREAD

**Issue by sethim** [nipy/heudiconv#316] opened 2019-03-03 01:29 UTC
### Platform details:

Choose one:
- [ ] Local environment

- [ ] Container

- Heudiconv version:

**Comment by sethim** [comment] 2019-03-03 01:30
Last login: Sun Mar  3 12:24:41 on ttys001
Mokshs-MacBook-Pro-2:~ msethi$ docker pull nipy/heudiconv:latest
Error response from daemon: manifest for nipy/heudiconv:latest not found
Mokshs-MacBook-Pro-2:~ msethi$

**Comment by satra** [comment] 2019-03-03 01:33
@sethim - to make clear that `latest`  is not a good tag, we have renamed it as `unstable`. a stable version will be created as soon as #315 is merged. you can pull using: `docker pull nipy/heudiconv:unstable`

**Closed** 2019-03-03 01:33 UTC

**Comment by sethim** [comment] 2019-03-03 02:04
Thanks

**Comment by kslays** [comment] 2019-04-26 18:40
The [DockerHub HeuDiConv website](https://hub.docker.com/r/nipy/heudiconv) shows following the Docker Pull Command in the upper right of the webpage: 
`docker pull nipy/heudiconv`
This is converted automatically to: 
`docker pull nipy/heudiconv:latest`
That results in the error message. All three [installation instructions on the HeuDiConv GitHub website](https://github.com/nipy/heudiconv) (the slides, BIDS tutorial, and Youtube video) all suggest this command and all result in this confusing error ([see question by Brian Odegaard at bottom](http://reproducibility.stanford.edu/bids-tutorial-series-part-2a/)). Something should be changed in the docs, because currently it is not clear how to use HeuDiConv with Docker at all.

**Comment by SamGuay** [comment] 2019-04-26 22:47
I agree with @kslays that the installation doc should be updated or at least point to this closed issue. For people who are unfamiliar with GitHub, they may struggle to find the answer in a **_closed_** issue. In fact, they may just never find it. I thought my computer was the problem until I found this issue! :upside_down_face: 

Cheers,

**Comment by mgxd** [comment] 2019-04-29 22:03
hi @SamGuay @kslays - we've since released `v0.5.4`, updated the slides, and readme on dockerhub to include instructions on using versioned releases. Hopefully this makes things much clearer :smiley:

**Comment by kslays** [comment] 2019-04-29 22:19
That's great, looks like v0.5.4 was a big release. 

The GitHub readme.md should be changed as well, under the section called, "Tutorial with example conversion to BIDS format using Docker." Perhaps with a note for the two "Other tutorials" section, because they both still refer to the latest tag, which has an obscure failure error.

**Comment by SamGuay** [comment] 2019-04-29 22:48
Great, thanks! I was trying to install it this past Friday by following the given instructions on here and in the tutorials. So I think @kslays' idea of putting a note or something would be great.

Thanks again!
