### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Maximiliun** [nipy/heudiconv#191] opened 2018-04-17 02:36 UTC
I get the following error:
< => docker run --rm -it -v /Volumes/DATA_SCIENCE/bids/dicoms:/dicoms \
 => -v /Volumes/DATA_SCIENCE/bids/output:/output nipy/heudiconv:latest
INFO: Running heudiconv version 0.5.dev1
Traceback (most recent call last):
  File "/opt/conda/envs/neuro/bin/heudiconv", line 11, in <module>
    load_entry_point('heudiconv==0.5.dev1', 'console_scripts', 'heudiconv')()
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 120, in main
    process_args(args)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/cli/run.py", line 240, in process_args
    heuristic = load_heuristic(args.heuristic)
  File "/opt/conda/envs/neuro/lib/python2.7/site-packages/heudiconv/utils.py", line 275, in load_heuristic
    if os.path.sep in heuristic or os.path.lexists(heuristic):
TypeError: argument of type 'NoneType' is not iterable>

What am I doing wrong?

**Comment by yarikoptic** [comment] 2018-04-17 03:29
you have provided no options, not even the heuristic to use (-f).  But I agree -- we should make argparse behave more informatively and spit out cmdline invocation options in such cases instead of allowing it to crash later on.  So I would consider it to be a duplicate of https://github.com/nipy/heudiconv/issues/173

**Closed by yarikoptic** 2018-04-17 03:29 UTC
