### ISSUE TITLE
Automatic placement of `echo` results in BIDS-invalid format

### ISSUE THREAD

**Issue by andrew-yian-sun** [nipy/heudiconv#541] opened 2022-02-01 19:11 UTC
### Summary

I'm trying to get the following BIDS-valid output:
`sub-0061_echo-1_part-mag_MEGRE.nii.gz` Related Github issue at bids-specification: [https://github.com/bids-standard/bids-specification/issues/979](url)

However, it seems like `echo` is automatically generated by HeuDiConv to appear directly before `_MEGRE`, making it BIDS invalid (`echo` has to come before `part`).

The relevant part of my heuristic:
`megre_mag = create_key('sub-{subject}/{session}/anat/sub-{subject}_{session}_part-mag_MEGRE')`

I omit `echo` because it otherwise will generate 2 instances of echo in my output.

### Platform details:

Choose one:
- [ ] Local environment

- [x] Container: Docker, nipy/heudiconv:latest

- Heudiconv version: 0.9.0

**Comment by pvelasco** [comment] 2022-02-01 19:26
Hi @andrew-yian-sun ,
I can work on a fix. However, to test it, would you be able to provide a sample dataset?
Ideally, a very low resolution, just a few echoes, on a phantom.
Thanks,
-Pablo

**Comment by andrew-yian-sun** [comment] 2022-02-01 21:36
@pvelasco Yes, I'll try to get that to you tomorrow. Thanks!

**Comment by tsalo** [comment] 2022-02-02 17:51
@pvelasco It looks like the keyword you used in #542 didn't auto-close this issue. Now that #542 is merged, can this be closed?

**Comment by pvelasco** [comment] 2022-02-02 18:02
I think so.

**Comment by tsalo** [comment] 2022-02-02 18:03
Sounds good. I'll close this now, but @andrew-yian-sun if you find that the problems persists, please feel free to follow up here.

**Closed by tsalo** 2022-02-02 18:03 UTC

**Comment by andrew-yian-sun** [comment] 2022-04-12 02:30
@tsalo I recently tried to the recent version of heudiconv, 0.10.0 but echo is still appearing in the wrong place:
it should be `sub-001_ses-1_echo-1_part-mag_MEGRE`
but I am being given: `sub-001_ses-1_part-mag_echo-1_MEGRE`

Is this issue still being fixed?

**Comment by tsalo** [comment] 2022-04-12 13:59
The issue should be fixed, but the most recent release, 0.10.0, was in October of last year, while the fix was merged in February of this year.

@yarikoptic is it maybe time for 0.11.0?

**Comment by pvelasco** [comment] 2022-04-12 14:11
Well, the problem is that I thought the `echo` entity came last, but I was mistaken 😞 : `part` is supposed to come after `echo` ([BIDS v1.5.0](https://bids-specification.readthedocs.io/en/v1.5.0/04-modality-specific-files/01-magnetic-resonance-imaging-data.html#task-including-resting-state-imaging-data) and later).

So I would need to fix that, but I'm a little time constrained right now. I'll try to fix it by the end of the week.

**Comment by yarikoptic** [comment] 2022-04-12 15:45
Thought to finish #544 before I do 0.11.0 but may be would need to cut it before then. That pr should make order follow bids schema thus guaranteed to be correct

**Comment by pvelasco** [comment] 2022-04-15 23:27
I take it back:
The fix works correctly: `part` comes after `echo`. We even check it explicitly [in the tests](https://github.com/nipy/heudiconv/blob/a1f63de34f23a3f6a2a750caaeb9631191988978/heudiconv/tests/test_bids.py#L1149-L1156)
@tsalo was correct: the problem is that the fix came after 0.10.0 was released.

So @andrew-yian-sun, when 0.11.0 is released (soon, hopefully), this issue should be fixed. If you can't wait and have `docker` installed, you can do a `docker build` of the `master` branch and use that for now.

**Comment by andrew-yian-sun** [comment] 2022-05-10 00:00
@pvelasco is this the correct way to use `docker build` on the `master` branch? 

```docker build https://github.com/nipy/heudiconv/#master:heudiconv```

If so, I get the following error:
```
[+] Building 0.0s (1/1) FINISHED                                                                                                         
 => [internal] load remote build context                                                                                            0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 7: unknown instruction: <!DOCTYPE
```

**Comment by pvelasco** [comment] 2022-05-10 12:18
Hi @andrew-yian-sun,

I haven't used `docker build` from URL before, so I'm not sure what the issue is.

From the [docker build documentation](https://docs.docker.com/engine/reference/commandline/build/#git-repositories), the correct command would be:
```
docker build https://github.com/nipy/heudiconv#master
```
1. You don't need a `/` (slash) before the `#` (pound) specifying the branch.
2. The `:<dir>` is used when you need to specify the build context (the folder with the files that Docker will use to build the image). For `heudiconv`, the build context is the repository root directory, so you don't need to specify it.

That said, using the command above returns a similar error:
```
Error response from daemon: dockerfile parse error line 7: unknown instruction: <!DOCTYPE
```

Just to check it, I downloaded a copy of the repo and tried to docker-build it from that local folder:

```
cd /tmp/
git clone --depth 1 -b master git@github.com:nipy/heudiconv.git
cd heudiconv/
docker build -t deleteme/heudiconv .
```
But that gave an error (at Step 11/13). So it looks like the `Dockerfile` might be broken.  So I have opened a new issue (#562) to address it.

**Comment by andrew-yian-sun** [comment] 2022-05-11 19:46
@pvelasco Just tried heudiconv v0.11.1, which worked as intended, thanks all!

**Comment by pvelasco** [comment] 2022-05-11 20:12
Glad it worked!
